- Gemfile
- Gemfile.lock
- app/controllers/changelogs_controller.rb
- app/services/changelogs_service.rb
- config/routes.rb
- db/migrate/20210328070841_create_applications.rb
- db/migrate/20210328071124_add_application_to_server.rb
- db/schema.rb
- spec/factories/application.rb
- spec/factories/server.rb
- spec/models/application_spec.rb
- spec/services/changelogs_service_spec.rb
If applied, this commit will ... [Add a service that receive an application id and generate changelogs. Add a controller that creates a json with the changelogs. Add a show route to applications and index route to changelogs.]
- minor change one
- minor change two
<MY_CARD_LINK>
<DESIGN_EXPECTED_SCREENSHOT>
<MY_SCREENSHOT or MY_GIF>
[Add here any other information you believe reviewers need to be aware of]
> Add changelogs service

- app/controllers/projects_controller.rb
- app/models/project.rb
- app/models/server.rb
- app/views/applications/_application.json.jbuilder
- app/views/applications/index.json.jbuilder
- app/views/applications/show.json.jbuilder
- app/views/servers/_server.json.jbuilder
- db/migrate/20210331214730_remove_name_from_server.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/server.rb
- spec/models/server_spec.rb
- spec/services/flows/deploy_notification_flow_spec.rb
- spec/services/flows/graylogs_incident_notification_flow_spec.rb
- spec/services/flows/sentry_incident_notification_flow_spec.rb
- spec/services/server_incident_service_spec.rb
update projects controller to return the applications
> update projects controller to return the applications

- app/views/applications/_application.json.jbuilder
If applied, this commit will Add 'repository' 'friendly name' as 'name' to 'application' view.
> Add 'repository' 'friendly name' as 'name' to 'application' view.

- app/services/flows/sentry_incident_notification_flow.rb
- spec/services/flows/sentry_incident_notification_flow_spec.rb
If applied, this commit will build the Sentry's link by Repository's source
N/A
https://github.com/codelittinc/roadrunner/issues/243
N/A
N/A
N/A
> Build Sentrys link by Repositorys source

- app/services/clients/github/branch.rb
- app/services/clients/github/parsers/commit_parser.rb
- app/services/commits_matcher.rb
- app/services/flows/sub_flows/base_release_sub_flow.rb
- app/services/flows/sub_flows/hotfix_release_stable_flow.rb
- app/services/flows/sub_flows/release_stable_flow.rb
https://github.com/codelittinc/roadrunner/issues/237
> Update, github branch return parsed commits

- app/services/clients/azure/branch.rb
https://github.com/codelittinc/roadrunner/issues/239
> Update azure client to return a parsed commit list

- app/services/clients/github/parsers/release_parser.rb
- app/services/clients/github/release.rb
- spec/fixtures/services/github_release.json
- spec/services/clients/github/parsers/release_parser_spec.rb
- spec/services/clients/github/release_spec.rb
https://github.com/codelittinc/roadrunner/issues/238
> Update github client to return a parsed release and release list.

- app/services/clients/azure/parsers/pull_request_parser.rb
- app/services/clients/azure/pull_request.rb
https://github.com/codelittinc/roadrunner/issues/239
> Update azure client to return a parsed pull request

- app/services/clients/azure/parsers/release_parser.rb
- app/services/clients/azure/release.rb
https://github.com/codelittinc/roadrunner/issues/239
> Update azure client to return a parsed release list

- app/services/tasks/server_task.rb
If applied, this commit will update ServerTask to handle Timeout response
N/A
https://github.com/codelittinc/roadrunner/issues/250
N/A
> Update server task to handle timeout response

- app/services/clients/source_control_client.rb
- app/services/flows/sub_flows/base_release_sub_flow.rb
- app/services/flows/sub_flows/hotfix_release_candidate_flow.rb
- spec/services/clients/source_control_client_spec.rb
If applied, this commit will add more methods to source control client
> add more methods to source control client

- app/models/release.rb
- db/migrate/20210512172707_add_deploy_status_to_release.rb
- db/schema.rb
- spec/models/release_spec.rb
https://github.com/codelittinc/roadrunner/issues/248
> Add deploy status to release model

- app/services/clients/source_control_client.rb
- app/services/flows/base_flow.rb
- app/services/flows/new_review_submission_flow.rb
- app/services/flows/release_by_repository_flow.rb
- app/services/flows/release_by_slack_channel_flow.rb
- app/services/flows/release_flow.rb
- spec/services/clients/source_control_client_spec.rb
https://github.com/codelittinc/roadrunner/issues/269
> Add source_control_client to BaseFlow and replace Github client for it on all flows

- app/services/flows/deploy_notification_flow.rb
- spec/services/flows/deploy_notification_flow_spec.rb
https://github.com/codelittinc/roadrunner/issues/249
> Updated latest release deploy_status when the a notification is deployed

- app/services/parsers/azure_webhook_source_control_parser.rb
- spec/fixtures/services/flows/azure_updated_pull_request.json
- spec/services/parsers/azure_webhook_source_control_parser_spec.rb
https://github.com/codelittinc/roadrunner/issues/274
> Pull requests with event_type updated create new pull request flow

- app/services/clients/source_control_client.rb
- app/services/create_repository_service.rb
- spec/services/clients/source_control_client_spec.rb
https://github.com/codelittinc/roadrunner/issues/273
> Update create_repository_service to use source control client instead of github client

- app/services/clients/azure/branch.rb
- app/services/clients/azure/pull_request.rb
- app/services/clients/azure/release.rb
- app/services/clients/github/branch.rb
- app/services/clients/github/hook.rb
- app/services/clients/github/pull_request.rb
- app/services/clients/github/release.rb
- app/services/clients/github/repository.rb
- app/services/clients/source_control_client.rb
- app/services/create_repository_service.rb
- spec/services/clients/azure/branch_spec.rb
- spec/services/clients/azure/release_spec.rb
- spec/services/clients/github/branch_spec.rb
- spec/services/clients/github/hook_spec.rb
- spec/services/clients/github/release_spec.rb
- spec/services/clients/github/repository_spec.rb
- spec/services/clients/source_control_client_spec.rb
- spec/services/commits_matcher_spec.rb
- spec/services/flows/hotfix_release_flow_spec.rb
- spec/services/flows/release_by_repository_flow_spec.rb
- spec/services/flows/release_flow_spec.rb
https://github.com/codelittinc/roadrunner/issues/282
> Update source control client methods to receive repository object ins tead of name string

- .github/workflows/prod_deploy.yml
- convox.yml
If applied, this commit will fix the convox prod deploy
> fix the convox prod deploy

- Gemfile
- Gemfile.lock
- app/assets/javascripts/rails_admin/custom/ui.js
- config/application.rb
- config/initializers/rails_admin.rb
If applied, this commit will ... [Please complete the description]
- minor change one
- minor change two
<MY_CARD_LINK>
[Add here any other information you believe reviewers need to be aware of]
> upgrade rails admin

- .gitignore
- app/services/tasks/azure_sprints_update.rb
If applied, this commit will Remove duplicated project in the AzureSprintsUpdate task
> Remove duplicated project in the AzureSprintsUpdate task

- app/controllers/applications_controller.rb
- app/models/application.rb
- app/views/applications/_form.html.erb
- app/views/applications/_table.html.erb
- app/views/applications/edit.html.erb
- app/views/applications/index.html.erb
- app/views/applications/new.html.erb
- app/views/repositories/_form.html.erb
- config/routes.rb
https://user-images.githubusercontent.com/6727150/187537650-3c45a8a6-1699-4ed2-8aaf-56fe358bf222.mov
> add crud for applications and servers

- app/services/admin/actions/replay_flow.rb
- app/services/clients/azure/branch.rb
- config/locales/en.yml
Update regex for commit type(sha1) and add translation key to rerun
> update regex for commit type(sha1)
